### ISSUE TITLE
Exception when using with Office 2016

### ISSUE THREAD

**Issue by matthiasburger** [ignatandrei/OneNoteOCR#4]
When starting, I get an exception on `InsertImage`.

System.Runtime.InteropServices.COMException: "Ausnahme von HRESULT: 0x80042030"

![image](https://user-images.githubusercontent.com/19508666/52850310-747d0200-3113-11e9-9b99-7adb63788320.png)

**Comment by ignatandrei** [comment]
Maybe you do not have OneNote on your account ? Please try to open OneNote

**Comment by matthiasburger** [comment]
sure:
![image](https://user-images.githubusercontent.com/19508666/52961725-e5cee600-339b-11e9-96ba-82b36a4fe44f.png)
I can open it, create notes, save,... works everything

**Comment by ignatandrei** [comment]
https://docs.microsoft.com/en-us/office/client-developer/onenote/error-codes-onenote


hrAppInModalUI | 0x80042030 | A modal dialog is blocking the app.


Do you have one node saying something?

**Comment by matthiasburger** [comment]
Ahhh yes, I never opened OneNote before. There was a dialogmessage - now it works. Thank you!!
And thanks for that error-code page. Didn't find that one
