### ISSUE TITLE
System.FormatException

### ISSUE THREAD

**Issue by Vitaliy-B** [ignatandrei/OneNoteOCR#6]
I have OneNote installed, I'm trying to use this dll, but always receive the error:

Error: System.Exception: System.FormatException: The input string had the wrong format.
    in System.Number.ParseSingle (String value, NumberStyles options, NumberFormatInfo numfmt)
    in System.Single.Parse (String s)
    in OneNoteOCRDll.OneNoteOCR.AttributeToFloat (XElement node, String name)
    in OneNoteOCRDll.OneNoteOCR. <OcrTexts> d__4.MoveNext ()
    in System.Linq.Buffer`1..ctor (IEnumerable`1 source)
    in System.Linq.Enumerable.ToArray [TSource] (IEnumerable`1 source)

The file that I'm trying to use: 
![scrsh01](https://user-images.githubusercontent.com/3762223/60018121-26fd3c80-9693-11e9-929c-82a7116868d5.png)

**Comment by ignatandrei** [comment]
You have the sources. Could you debug?
